# permissions for end users to view autoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: autoscaler-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: autoscaling-operator
    app.kubernetes.io/part-of: autoscaling-operator
    app.kubernetes.io/managed-by: kustomize
  name: autoscaler-viewer-role
rules:
- apiGroups:
  - k8s.charolia.io
  resources:
  - autoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.charolia.io
  resources:
  - autoscalers/status
  verbs:
  - get
