---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - k8s.charolia.io
  resources:
  - autoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.charolia.io
  resources:
  - autoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.charolia.io
  resources:
  - autoscalers/status
  verbs:
  - get
  - patch
  - update
