apiVersion: k8s.charolia.io/v1beta1
kind: AutoScaler
metadata:
  labels:
    app.kubernetes.io/name: autoscaler
    app.kubernetes.io/instance: autoscaler-sample
    app.kubernetes.io/part-of: autoscaling-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: autoscaling-operator
  name: autoscaler-sample
  namespace: default
spec:
  minReplicaCount: 0
  scaleTargetRef:
    name: nginx
    type: deployment
  triggers:
  - type: cron
    metadata:
      timezone: Europe/Berlin
      start: "*/2 * * * *" # every 2 minutes
      end: "*/5 * * * *" # every 5 minutes
      desiredReplicas: 5
